### ISSUE TITLE
Can we use our own Docker image that is a child image of readthedocs/build? 

### ISSUE THREAD

**Issue by tlvu** [readthedocs/readthedocs-docker-images#106]
We busted the limit of memory when installing extra packages during the build, see https://github.com/Ouranosinc/raven/issues/148
```
conda env create --quiet --name stable --file environment.yml
Collecting package metadata: ...working... done
Solving environment: ...working... Killed

Command killed due to excessive memory consumption
```

So by providing our own docker image, we would solve that memory problem and plus each build will be faster since there will not be any install needed and each build will be 100% reproducible since all the versions will be locked down inside the docker image.

**Comment by stsewd** [comment]
We don't support that. There is not plans to support a feature like that, we are focusing in https://github.com/rtfd/readthedocs.org/issues/1083

**Comment by ericholscher** [comment]
Similarly, I'd suggest looking at using autoapi, which parses docstrings instead of importing them. That way we don't need to install your entire dependency chain to pull docstrings off code: https://sphinx-autoapi.readthedocs.io/en/latest/reference/directives.html

**Comment by tlvu** [comment]
To close on this and help other users that might be in similar situation if they use sphinx autodoc feature, I managed to solve my `excessive memory consumption` by mocking all the dependencies I do not need to generate docs for, so I do not have to install them.  See details in my PR that fixed the problem https://github.com/Ouranosinc/raven/pull/167.
