### ISSUE TITLE
Add `/home/docs/node_modules/.bin` to PATH

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-docker-images#108]
It would be good to add this directory to the PATH so we can use these commands when building.

I'm currently doing this as a workaround when building.

```python
os.environ['PATH'] = '/home/docs/node_modules/.bin/:{}'.format(os.environ.get('PATH'))
```

**Comment by stsewd** [comment]
> I'm currently doing this as a workaround when building.

Do you mean when building documentation or when you build the docker images? I think we delete the whole path env when building.

**Comment by humitos** [comment]
When building documentation. I'm adding that into a `conf.py` file for now.

**Comment by stsewd** [comment]
https://github.com/readthedocs/readthedocs.org/blob/02338dff89f3cd554752d9bd22feab95b90f683b/readthedocs/vcs_support/base.py#L80-L80

Looks like we only delete it when doing vcs operations
