### ISSUE TITLE
Using apt-get to install other dependencies

### ISSUE THREAD

**Issue by jakirkham** [readthedocs/readthedocs-docker-images#114]
Is it or would it be possible to install other system-level dependencies with `apt-get`?

**Comment by stsewd** [comment]
Yes, but we don't allow executing arbitrary commands in the build process. But if you are using sphinx, you can run those commands in the `conf.py` file.

**Comment by humitos** [comment]
If the dependency is widely used for building documentation, we usually install it in our own image and make a new release after some time.

As @stsewd mentioned, we don't allow executing arbitrary commands. The usage of `conf.py` is a hack to our current process and it's not supported --although, it could work/be enough in your case.

**Comment by jakirkham** [comment]
It seems like "widely used" might be subjective. For instance `libnuma` is widely used in the HPC space, but it might not be something you want to add to the container. We can imagine other such examples.

So my question is could we provide a file with a list of dependencies we would like to have `apt-get install`ed for us. This avoids arbitrary commands being run, but still allows users some flexibility here.

It sounds like the answer to this question is not today. Though users may be able to hack around this. Does this seem like the sort of thing that could be in scope in the future?

**Comment by sergei-maertens** [comment]
This is also relevant for use, we require libgdal for the Sphinx build. It looks like we'll be able to work around it by making the call in `conf.py`, but an option in the config file to specify a list of package names to install would be great!

**Comment by jakirkham** [comment]
@sergei-maertens, have you looked at Conda? RTD supports that already and there is a package for GDAL there.

**Comment by sergei-maertens** [comment]
I didn't, will do when it becomes relevant again!

**Comment by razvnane** [comment]
> Yes, but we don't allow executing arbitrary commands in the build process. But if you are using sphinx, you can run those commands in the `conf.py` file.

Is there a way to install bison >=3.0 and flex >=2.6 as prerequisites to the build process?

**Comment by jakirkham** [comment]
Also would checkout Conda support, @razvnane 🙂

**Comment by felix-hilden** [comment]
Just to pile on: I would also like this feature, and the requirement file for other packages sounds like a reasonable suggestion. I don't need arbitrary commands either. My attempt was using `graphviz` for generating images which I would loathe to have in the repository. In addition to a Python package, it requires executables available in the Ubuntu repositories.

Thanks for the `conf.py` hack though 😅 I guess installing things in the same process doesn't suffer nearly as much on Linux as it does on Windows, the `PATH` not updating and the binaries being generally all over the place instead of a single folder.

**Comment by jakirkham** [comment]
There’s also a Conda package for Graphviz if you want to give that a try, Felix 🙂

**Comment by humitos** [comment]
Hi! I suggest you to subscribe to this PR https://github.com/readthedocs/readthedocs.org/pull/8065/ that implements a new config in `.readthedocs.yaml` that allow users to install packages via APT. Once it gets merged and deployed you will be able to install these packages by yourself.
