### ISSUE TITLE
How tu run the Docker Images

### ISSUE THREAD

**Issue by wisoez** [readthedocs/readthedocs-docker-images#119]
Hi there,
I pull from Docker Hub:
# docker pull readthedocs/build:latest

And run this image:
# docker run -it --name readthedocs -p 80:80 -d readthedocs/build:latest

But it doesn't work :(

**Comment by humitos** [comment]
Hi @wisoez! We use this image internally as part of https://github.com/readthedocs/readthedocs.org project to build the documentation.

These images can't be used in a standalone mode. What are your trying to achieve?

**Comment by davidfischer** [comment]
If you're trying to run Read the Docs itself either for development or just to try it out, you want to look at this guide: https://docs.readthedocs.io/en/stable/development/standards.html
