### ISSUE TITLE
Add Rust to the docker image?

### ISSUE THREAD

**Issue by alex** [readthedocs/readthedocs-docker-images#135]
Hello!

For pyca/cryptography, we're in the process of adding Rust code to our python package. However, this means our docs fail to build. Oh no!

If the docker image had a recent rust installed, that'd get us back on track. Here's the steps we use in our own docker images to install Rust:

```dockerfile
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
ENV PATH="/root/.cargo/bin:$PATH"
```

**Comment by stsewd** [comment]
If you are using sphinx, you can install rust from the `conf.py` file as a workaround.

**Comment by alex** [comment]
If I submit a PR for this repo, is that something that'd be accepted?

**Comment by stsewd** [comment]
There is a design decision from the core team to make before that, but I don't think rust is a common dependency in the python ecosystem.

**Comment by alex** [comment]
I agree it's not _yet_ common, we're hoping that integration into pyca/cryptography (which is relatively widely used) will help change that :-)

**Comment by ericholscher** [comment]
We had a team meeting this morning, and discussed this. We have a medium-term goal of supporting more custom docker images, but for now we agreed that we should add Rust to the default image.
