### ISSUE TITLE
Add support for python 3.9

### ISSUE THREAD

**Issue by mlech-reef** [readthedocs/readthedocs-docker-images#140]
![image](https://user-images.githubusercontent.com/63924630/95346481-30c4a680-08bc-11eb-9fff-c8b4cc1cc241.png)

Python 3.9 has been released two days ago.

**Comment by humitos** [comment]
Hi @mlech-reef! This is in our radar (in fact our image 8.0 already have Py3.9rc installed on it). However, it's not published and ready to be used by users yet. I don't have an ETA for this unfortunately.

**Comment by mlech-reef** [comment]
Thank you for the update. I will switch to 3.8 for now

**Comment by ThiefMaster** [comment]
Unfortunately using 3.8 doesn't work when you enable pip-installing and have `python_requires` set in your package's metadata... :/

> ERROR: Package 'indico' requires a different Python: 3.8.6 not in '~=3.9'

**Comment by ThiefMaster** [comment]
OK, for now I found a workaround to build with 3.8: https://github.com/indico/indico/commit/a3c2eb4ecdf492102e0ef399e6092ed862b7c9a4

Wouldn't work with a setup.cfg though (which I'd like to start using at some point), so still hoping to get proper 3.9 support soon :)

**Comment by ThiefMaster** [comment]
Bump, any news?

**Comment by pradyunsg** [comment]
Ahoy! Anything that can be done to help move this forward?

**Comment by ThiefMaster** [comment]
```
build:
  image: testing
```

in `.readthedocs.yml` helps

**Comment by pradyunsg** [comment]
From the README here:

> readthedocs/build:8.0
>     testing Ubuntu 20.04 supporting Python 2.7, 3.5, 3.6, 3.7, 3.8, 3.9.0rc1 and PyPy3.5-7.0.0. For internal development testing only, not available for public usage yet.

**Comment by ThiefMaster** [comment]
It works.

**Comment by staticdev** [comment]
@humitos is there a circular dependency here? readthedocs-docker-images is waiting for readthedocs.org to update and vice-versa?

**Comment by humitos** [comment]
@staticdev if you need Python 3.9, you can use `testing` image for now.

We are discussing the new structure for our Docker images at https://github.com/readthedocs/readthedocs.org/pull/7566. However, it will take some time to be implemented and ready to use.

**Comment by rjplevin** [comment]
I'm astounded that this is still a problem in 2023. Python 3.11 is out and 3.12 in alpha, but RTD is still not supporting 3.9 or later?

**Comment by rjplevin** [comment]
Thanks. I see now that the syntax in my yml file has been designated "legacy".
