### ISSUE TITLE
Add support for Python `3.10dev`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-docker-images#152]
When upgrading to Ubuntu 20.04 it would be good to include Python 3.10dev together with Python 3.9 so we allow start testing Python 3.10 before it gets released. Once it's released, we can just update to the 3.10.0 version.

**Comment by pradyunsg** [comment]
Ahoy! Anything that can be done to help move this forward?

**Comment by humitos** [comment]
I opened #174 and we hope to review, merge and deploy soon 😃

**Comment by humitos** [comment]
This is already done. You can use the `build.image: testing` image and `python.version: "3.10"` now in the YAML config file.
