### ISSUE TITLE
Add dependencies to allow pycairo and pygobject installation for sphinxcontrib-shoebot

### ISSUE THREAD

**Issue by stuaxo** [readthedocs/readthedocs-docker-images#162]
Hi,
   For Shoebot we use pycairo along with pygobject to access pango and rsvg.
Would it be possible to add the dependencies for these?

This would allow us to generate images using sphinxcontrib-shoebot, our extension that renders images with shoebot.

I had a poke at the rtd dockerfile and was able to get things working using

```
libgirepository1.0-dev   # This lets us install pygobject and pycairo, both of which only compile from source.
gir1.2-pango-1.0         # Gobject bindings for Pango, which we use to render text
gir1.2-rsvg-2.0          # Gobject bindings for Rsvg, so we can output to svg
```

Thanks
Stuart

**Comment by stuaxo** [comment]
https://github.com/shoebot/shoebot/
https://github.com/shoebot/sphinxcontrib-shoebot/

https://shoebot.readthedocs.io/en/latest/

This will let us render inline examples in our docs, and enable other projects that use pycairo and pango that may want to render examples in their docs.

**Comment by humitos** [comment]
Hi! I suggest you to subscribe to this PR https://github.com/readthedocs/readthedocs.org/pull/8065/ that implements a new config in `.readthedocs.yaml` that allow users to install packages via APT. Once it gets merged and deployed you will be able to install these packages by yourself.

**Comment by stuaxo** [comment]
Thanks looking at this, and for the link.
