### ISSUE TITLE
Missing how to run documentation

### ISSUE THREAD

**Issue by MrAmbiG** [readthedocs/readthedocs-docker-images#163]
Hi Team,
There is no documentation provided either in github or docker hub on how to run the docker image. Please provide any documentation on running docker images with available customization options like port, environment variables etc.,

**Comment by stsewd** [comment]
Hi, the images here are used to encapsulate the build process, if you want to run a Read the Docs instance, you can check https://docs.readthedocs.io/en/stable/development/standards.html#set-up-your-environment
