### ISSUE TITLE
make libclang available?

### ISSUE THREAD

**Issue by polwel** [readthedocs/readthedocs-docker-images#167]
I am trying to use [sphinx-c-autodoc](https://sphinx-c-autodoc.readthedocs.io/en/latest/index.html) with RTD. It currently chokes because libclang is not installed.
```
clang.cindex.LibclangError: libclang-11.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
```
Any chance?

**Comment by humitos** [comment]
We are adding the ability to install packages via APT in this PR https://github.com/readthedocs/readthedocs.org/pull/8065/ . I recommend you to subscribe there to follow the process and get a notification when gets merged so you can install it by yourself after it's deployed.
