### ISSUE TITLE
Update Rust

### ISSUE THREAD

**Issue by Daggy1234** [readthedocs/readthedocs-docker-images#169]
Hey rust version 1.46 is kinda old now.

Bumping the rust version would be extremely cool. 1.50+ is now stable and should  be a good benchmark.

Or letting us specify the version would also be great

**Comment by humitos** [comment]
> Or letting us specify the version would also be great

We wrote a design document for this. It's not implemented yet, tho. See 
https://docs.readthedocs.io/en/stable/development/design/build-images.html#specifying-extra-user-s-dependencies

**Comment by Daggy1234** [comment]
I'll close the issue and keep the PR open #170
