### ISSUE TITLE
Migrate off `travis-ci.org`

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs-docker-images#171]
> Hi! It seems there are still plenty of builds running. We're pushing back the shutdown date to June 15th. Please consider migrating to travis-ci.com.

![Screenshot 2021-06-08 at 11-25-15 Build #1218 - readthedocs readthedocs-docker-images - Travis CI](https://user-images.githubusercontent.com/316517/121160268-39ef8400-c84c-11eb-8de3-874677163351.png)

That's 1 week from now.

**Comment by stsewd** [comment]
We could migrate to travis-ci.com or a circle, we have migrated all of our projects to circle, so that would be the default choice.

**Comment by astrojuanlu** [comment]
Being addressed in #174

**Comment by astrojuanlu** [comment]
Closed in #174
