### ISSUE TITLE
testing != 7.0

### ISSUE THREAD

**Issue by DrewDevereux** [readthedocs/readthedocs-docker-images#177]
The ``README.md`` states that ``readthedocs/build:testing`` == ``readthedocs/build:7.0``, but this is not the case. ``:7.0`` contains ``python 3.9``, but ``:testing`` does not:
```
me@mine:~$ docker run -ti readthedocs/build:testing bash
docs@38ccaab061da:/$ python3.8 --version
Python 3.8.6
docs@38ccaab061da:/$ python3.9 --version
bash: python3.9: command not found
docs@38ccaab061da:/$
```

**Comment by humitos** [comment]
Hi @DrewDevereux! These images are for internal Read the Docs usage and for development. They are tagged in our servers and locally but maybe wrong in Docker Hub.

Besides we are changing our structure and none of these images are going to be used anymore.

What do you want to use these images for?

**Comment by astrojuanlu** [comment]
I thought we had addressed the inaccuracies of the `README` in #172, however I am now confused as well.

**Comment by DrewDevereux** [comment]
Hi @humitos,
Two reasons:
1. We build our docs in our CI pipeline, in order to be confident that they will build correctly on RTD. Therefore it makes sense for our CI pipeline build process to mimic as closely as possible the RTD build process. Thus our CI pipeline builds our docs in a readthedocs/build container.
2. We embed UML diagrams in our docs using sphinxcontrib-plantuml, which needs PlantUML to be installed. Your docker images are a very convenient way to get that.

**Comment by humitos** [comment]
> We build our docs in our CI pipeline, in order to be confident that they will build correctly on RTD, so it makes sense for our CI pipeline build process to mimic as closely as possible the RTD build process. Therefore our CI pipeline builds our docs in a readthedocs/build container

Why not using "Pull Request builders" instead of mimic Read the Docs? See https://blog.readthedocs.com/pull-request-builder-general-availability/

**Comment by DrewDevereux** [comment]
That looks sensational. I'll give it a go, thanks.
