### ISSUE TITLE
Upload build tools to AWS fails

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-docker-images#191]
See https://app.circleci.com/pipelines/github/readthedocs/readthedocs-docker-images/264/workflows/900786a7-f65d-44fa-b915-dbcdea8b7eee/jobs/466

@agjohnson I think there are some credential missings in CircleCI.

**Comment by agjohnson** [comment]
I already rotated the new keys in a while back, and didn't change permissions. Not sure what would be the case here.

**Comment by humitos** [comment]
There is a user along for a newer version of Rust. I'll see if I can grab some time to do this and make that user happy 😊

**Comment by humitos** [comment]
It seems there was an environment variable missing. A typo actually. We are using `ORG_AWS_ACCESS_KEY_ID` in the script, and the variables was named `ORG_AWS_ACCESS_KEY`

**Comment by humitos** [comment]
It worked. It seems that was the only issue here. All the compiled versions were uploaded successfully to S3 💯
