### ISSUE TITLE
Rebuild 20.04 build tools against libssl > 1.1.1

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs-docker-images#196]
Noting for later, but sometime before September 2023 we will need to rebuild all of our build tools against libssl > 1.1.1. The urllib3 package will be deprecating libssl 1.1.1 in September and we will have another issue similar to the Ubuntu 18.04 libssl issue that we just patched in our old build images.

The fix here will be slightly similar, but because our build tool binaries are separate from our build image it will be far easier to resolve the trouble with the build image.

Just guessing based on the fix we landed on, but something like:

- Install libssl dev headers for version > 1.1.1 (22.04 uses a libssl 3.0.2, maybe match this?)
- Rebuild all of the Python binaries packages and upload
- We shouldn't need to worry about hacking around to uninstall the libssl headers afterwards for the 20.04 image at least

**Comment by humitos** [comment]
Now, after clarifying the situation in https://github.com/readthedocs/blog/issues/222, we can say **we don't have to re-compile and re-build Ubuntu 20.04 image**. However, we _should_ probably if it's not hard.

**Comment by agjohnson** [comment]
Lets check back on this and gauge what usage of this image looks like as more users upgrade/add a configuration file. If there are a lot of users, we could take this work on. I don't think it would be hard to replicate your fix to 20.04 image and rebuild all of the Python versions for the image.

**Comment by humitos** [comment]
The last 90 days we have 0 builds with Ubuntu 20.04: https://ethicalads.metabaseapp.com/question/476-projects-using-ubuntu-20-04?days=90 -- which calls my attention. Maybe that query is not correct.

In that case, I don't think we should spend time on this 😄 : we don't have too many users using this image and also it's not going to be a problem based https://github.com/readthedocs/readthedocs-docker-images/issues/196#issuecomment-1580297176. So, we are fine not rebuilding this image and moving forward.

**Comment by agjohnson** [comment]
Do we want to close this out then? We're 8 months out from 24.04, though we haven't discussed if we are actually deprecating build support for 20.04 at that point yet either. But come April 2024 we'll have 3 supported build OS versions, and 20.04 should further drift down in usage.

**Comment by humitos** [comment]
I'm fine closing this issue, yes.

> We're 8 months out from 24.04, though we haven't discussed if we are actually deprecating build support for 20.04 at that point yet either. But come April 2024 we'll have 3 supported build OS versions, and 20.04 should further drift down in usage.

I'm happy to discuss a policy about this and stick to the defined plan. I think we will need to support 3 images for some period (like 6 months for example). Another option is to call Ubuntu 20.04 deprecated 6 month before 24.04 is released and remove its support once we add support for 24.04

**Comment by agjohnson** [comment]
Overlapping support for 20.04 and 24.04 would be best at very least, maybe call 2024-01-01 the EOL for the image? Supporting 3 OS shouldn't be much work with all of the images and build tools split up. The largest constraint being build time of 3 OS images worth of build tools probably.

Anyways, nothing we have to worry about until after we have 24.04 support out probably. I'll close up this issue here and we can revisit LTS deprecation.
