### ISSUE TITLE
Give some love to the Dockerfile

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-docker-images#60]
It would be awesome to follow some of the tips and tricks to build good Docker images like:

* [ ] use multi stage builds
* [x] remove all residuals after apt
* [ ] remove pyenv build environments after compiling
* [ ] remove all pyenv dependencies installed via apt
* [ ] ``--squash``, although it's in experimental :/
* [x] delete miniconda `.sh` file after installed
* [x] wget `master.zip` pyenv instead of clone it
* [x] pip cache (`--no-cache-dir` should be useful)
* [ ] more?

Ref: https://docs.docker.com/v17.09/engine/userguide/eng-image/dockerfile_best-practices/

**Comment by humitos** [comment]
Just built 18.04 image from #59 

```
readthedocs/build  18.04  27e5be0051e1  2 minutes ago  7.33GB
```

**Comment by graup** [comment]
Is there a rough timeline for when we can use the 4x version in our builds?

**Comment by bebehei** [comment]
`--squash` won't be a good choice. This docker image keeps adding files layer by layer. It does not change, delete or replace any files.

**Comment by bebehei** [comment]
`use multistage builds`: This might shave off some hundred MBs in the image.

I'm not deep into the rtd project internals yet. So how many of those `-dev` packages are superfluous after the build?

**Comment by varac** [comment]
Yes please, the insane size of the image holds me back from using it, really  ([readthedocs/build:7.0](https://hub.docker.com/layers/readthedocs/build/7.0/images/sha256-a82fb24c9405fb7e52e8fea66fa14648848abe840c915f985bb8c84a3c66c742?context=explore) is ~3gb big).
