### ISSUE TITLE
Segfault during conda install

### ISSUE THREAD

**Issue by saraedum** [readthedocs/readthedocs-docker-images#83]
I am trying to build documentation for a library that builds on [sagemath/sage](https://github.com/sagemath/sage) on readthedocs at https://github.com/MCLF/mclf/pull/107. Previously I had used some mocking to make this work without installing sage. Now, I tried to make this work without mocking and installed [sagelib](https://github.com/conda-forge/sagelib-feedstock) from conda-forge through an `environment.yml` file.

However, I could not get this to work. It seems that depending on the docker image version I specify in my readthedocs.yml, I either get an exit code 247 during the creation of the conda environment (Is that "out of RAM"?) or just a generic `There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (8190226).`

Trying to reproduce this outside of the readthedocs build system with the docker images from the docker hub, I ran into issues such as segfaults during a `conda install`, https://circleci.com/gh/MCLF/mclf/1437.

The segfaults go away if I upgrade the conda in the docker image.

So the question is: Can we upgrade the conda version in any of the versions available on readthedocs? Or are these considered frozen and I have to wait for the 3.0 to be made available?

**Comment by humitos** [comment]
There is a feature flag that can be enabled per project now: `UPDATE_CONDA_STARTUP`. See https://docs.readthedocs.io/en/latest/guides/feature-flags.html

Let me know if you want me to enable that setting in your project. In that case, please open an issue in https://github.com/readthedocs/readthedocs.org requesting this. Thanks!
